services:
  web:
    build: .
    container_name: thierrypfister-web
    restart: unless-stopped
    environment:
      - PFSTR_API_URL=http://192.168.1.111:8080
    networks:
      - proxy

networks:
  proxy:
    external: true
